document.write(<nav>)
		document.write("<ul>")
			document.write("<div>')
				document.write("<li><a href="index.html">Home</a></li>")
			document.write("</div>")
			document.write("<div>")
				document.write("<li><a href="about.html" >About</a></li>")
			document.write("</div>")
			document.write("<div>")
				document.write("<li><a href="projects.html" >Projects</a></li>")
			document.write("</div>")
			document.write("<div>")
				document.write("<li><a href="contact.html">Contact</a></li>")
			document.write("</div>")
		document.write("</ul>")
document.write("</nav>")